### ISSUE TITLE
TESSERACT_DATA_PATH and tesseract 3.03_rc1

### ISSUE THREAD

**Issue by netfab** [ruediger/VobSub2SRT#45]
Hi,

My system is gentoo.
If I use the ebuild from packaging/, vobsub2srt is working fine with tesseract-3.02.
But, if I upgrade tesseract to 3.03_rc1, vobsub2srt fails like this :
> $ vobsub2srt 01
> Error opening data file /usr/share/tesseract-ocr/tessdata/fra.traineddata
> Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
> Failed loading language 'fra'
> Tesseract couldn't load any languages!
> Failed to initialize tesseract (OCR).

The only way I found to make it work with tesseract 3.03_rc1 is to rebuild vobsub2srt to force TESSERACT_DATA_PATH at configure phase, like following in the ebuild :

```
src_configure() {
      local mycmakeargs=(
              -DTESSERACT_DATA_PATH="/usr/share"
      )
      cmake-utils_src_configure
}
```
So my question is : why do I need to force the TESSERACT_DATA_PATH value with tesseract 3.03_rc1 but not with 3.02 ? Is this normal ?

Thanks.

**Comment by ruediger** [comment]
What's the location of the `tessdata` directory? `/usr/share/tessdata`? Is that something which is set by Gentoo or a change in tesseract?

Right now VobSub2SRT does not try to detect the correct `TESSERACT_DATA_PATH` but simply assumes `/usr/share/tesseract-ocr/tessdata`.  That was never optimal and should be detected in the CMake script.

**Comment by netfab** [comment]
> What's the location of the tessdata directory? /usr/share/tessdata?
Yes. In both versions. Currently it is not set by Gentoo.

But it seems that the tessdata directory behavior has changed between 3.02 and 3.03,  please see \:
https://code.google.com/p/tesseract-ocr/issues/detail?id=938
https://code.google.com/p/tesseract-ocr/source/detail?r=e66d43390782f056b9be6e4aee4bf35c214a2f2d

**Comment by ruediger** [comment]
Does it work if you compile it without specifying `TESSERACT_DATA_PATH` and instead call it with

```
$ vobsub2srt --tesseract-data "" 01
```

**Comment by netfab** [comment]
No, same error.

**Comment by ruediger** [comment]
*sigh* I thought "" would set it to the default ([`tesseract_->datadir`](https://code.google.com/p/tesseract-ocr/source/diff?spec=svne66d43390782f056b9be6e4aee4bf35c214a2f2d&r=e66d43390782f056b9be6e4aee4bf35c214a2f2d&format=side&path=/api/baseapi.cpp)?). I guess I'll have to look into it. Since it's an rc, you have a workaround, and I'm currently short on time this has to wait a bit though (unless you come up with a backward compatible patch :))
