### ISSUE TITLE
**REMOVED**

### ISSUE THREAD

**Issue by NemoSciri** [ruediger/VobSub2SRT#76]
**REMOVED**

**Comment by StrawsonDesign** [comment]
I'm seeing similar build errors in debian buster with tesseract 4. small snippet:

/usr/include/tesseract/baseapi.h:464:75: error: ‘nullptr’ was not declared in this scope
     return GetComponentImages(level, text_only, false, 0, pixa, blockids, nullptr);
                                                                           ^~~~~~~
/home/james/git/media_scripts/VobSub2SRT/src/vobsub2srt.c++: In function ‘int main(int, char**)’:
/home/james/git/media_scripts/VobSub2SRT/src/vobsub2srt.c++:218:3: error: ‘TessBaseAPI’ has not been declared
   TessBaseAPI::SimpleInit(tess_path, tess_lang, false); // TODO params


sadly my old binaries from debian stretch don't work in buster anymore with the new tesseract.
